language: php

php:
    - 5.3
#    - 5.4

before_script:
    - composer install --dev

script:
    - phpunit
    - vendor/bin/phpcs -np --extensions=php --ignore=vendor/*,Tests/* --standard=ruleset.xml .