language: php

php:
    - 5.3
#    - 5.4

before_script:
    - composer install --dev
    - pyrus install pear/PHP_CodeSniffer
    - phpenv rehash

script:
    - phpunit
    - phpcs -np --extensions=php --ignore=vendor/*,Tests/* --standard=PSR2 .